modLoader="javafml"
loaderVersion="[${NEOFORGE},)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/AppliedEnergistics/Applied-Energistics-2/issues"

[[mods]]
modId="appliedenergistics2"
version="${version}"
displayName="Applied Energistics 2"
